services:
  ktor-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
  postgres_db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ktor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s